#!/bin/bash

# 本脚本用于初始化commitizen, 并将语言设置为中文。
# commitizen 用于规范提交内容，通过选择的方式书写commit message
# 使用方式
#     1. 首先将本脚本放置在/usr/local/bin目录下
#     2. 然后执行命令sudo chmod +x /usr/local/bin/cz-init
#     3. 在需要初始化commitizen的项目目录下执行命令cz-init

# 参考: https://www.jianshu.com/p/d264f88d13a4

if [ ! -d "node_modules" ]; then
    echo "未找到node_modules文件夹!"
    exit 1
fi

if [ ! -f "package-lock.json" ] && [ ! -f "yarn.lock" ] && [ ! -f "pnpm-lock.yaml" ]; then
    echo "未找到lock文件!"
    exit 2
fi

echo "初始化中..."

npm -g install commitizen@latest conventional-changelog-cli@latest conventional-changelog@latest

if [ -f "package-lock.json" ]; then
    commitizen init cz-conventional-changelog --save-dev --save-exact --force
    npm install --save-dev cz-conventional-changelog-zh
fi

if [ -f "yarn.lock" ]; then
    commitizen init cz-conventional-changelog --yarn --dev --exact --force
    yarn add -D cz-conventional-changelog-zh
fi

if [ -f "pnpm-lock.yaml" ]; then
    pnpm install -D cz-conventional-changelog-zh
    commitizen init cz-conventional-changelog --pnpm --save-dev --save-exact --force
fi

npx pkg set config.commitizen.path="./node_modules/cz-conventional-changelog-zh"

if [ ! -d ".git" ]; then
    git init
fi

echo "初始化完成！"

echo -e "\033[32m 请先将改动加到git暂存,然后使用git cz命令进行提交 \033[0m"
